create table CUSTOMERS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
  CITY CHAR(20),
  COUNTRY CHAR(20),
  PHONE INTEGER
);

create table ORDERS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DATE TIMESTAMP default CURRENT_TIMESTAMP(),
  CUSTOMER_ID INTEGER,
  constraint ORDERS_CUSTOMERS_ID_FK
  foreign key (CUSTOMER_ID) references CUSTOMERS
);

create table PRODUCTS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(100),
  PRICE DECIMAL not null,
  DESCRIPTION VARCHAR(1000),
  STOCK INTEGER
);

create table ORDER_ITEMS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ORDER_ID INTEGER,
  PRODUCT_ID INTEGER,
  QUANTITY INTEGER default 1,
  constraint ORDER_ITEMS_ORDERS_ID_FK
  foreign key (ORDER_ID) references ORDERS,
  constraint ORDER_ITEMS_PRODUCTS_ID_FK
  foreign key (PRODUCT_ID) references PRODUCTS
);