package vu.lt.mybatis.dao;

import java.util.List;


import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Player;


@Mapper
public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *ß
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    Player selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    List<Player> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    int updateByPrimaryKey(Player record);
}